In [1]:
from transformers import BertTokenizer
import numpy as np

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

long_sentences = [
    [
        "What is Cybersecurity?",
        "Cybersecurity is the practice of protecting systems, networks, and programs from digital attacks, theft, or damage. These cyberattacks usually aim to access, alter, or destroy sensitive information, extort money, or disrupt normal business operations. Key components include:\n"
        "- Network Security: Protecting network integrity and data.\n"
        "- Application Security: Securing applications by identifying vulnerabilities.\n"
        "- Information Security: Ensuring data privacy and integrity.\n"
        "- Operational Security: Managing data handling and protection practices.\n"
        "Methods such as firewalls, encryption, antivirus software, and multi-factor authentication (MFA) are employed to mitigate cyber threats."
    ],
    [
        "What is Malware?",
        "Malware, short for malicious software, refers to any software designed to cause harm to a computer, network, or server. It is used by attackers to steal data, spy on users, or damage systems. Types of malware include:\n"
        "- Viruses: Infect programs and replicate.\n"
        "- Worms: Spread independently across networks.\n"
        "- Trojan Horses: Disguised as legitimate software but deliver malicious payloads.\n"
        "- Ransomware: Encrypts data and demands payment for decryption.\n"
        "- Spyware: Collects and transmits user data secretly.\n"
        "- Adware: Shows unwanted ads and may track user data.\n"
        "Entry points include infected websites, email attachments, and social engineering."
    ],
    [
    "What is Phishing?",
    "Phishing is a type of cyberattack where attackers impersonate legitimate entities to trick individuals into revealing sensitive information such as usernames, passwords, or financial details. Phishing typically occurs through deceptive emails, websites, or messages that appear to come from trusted sources.\n"
    "Common types of phishing attacks include:\n"
    "- Spear Phishing: Targeted attacks aimed at specific individuals or organizations.\n"
    "- Whaling: Phishing attempts directed at high-profile targets like executives or senior management.\n"
    "- Smishing: Phishing conducted through SMS text messages.\n"
    "- Vishing: Voice-based phishing scams.\n"
    "Phishing is often identified by suspicious links, urgent requests for personal information, and poor grammar in communications. Users can protect themselves by scrutinizing sender details, avoiding clicking on unverified links, and enabling multi-factor authentication."
]
]
ma=86
l=sorted(long_sentences,key=len,reverse=True)
max_length=ma
TOKEN_IDS=[]
i=0
SEGMENT_IDS=[]
for sentence in long_sentences:
    encoded_input = tokenizer(
        sentence[0],sentence[1],
        max_length=max_length,      
        truncation=True,     
        padding="max_length"
    )
    tokens = tokenizer.convert_ids_to_tokens(encoded_input["input_ids"])
    
    print(f"Question: {sentence[0][:]}...")  
#     print(f"Answer:{sentence[1]:[:]}...")
    print(f"Tokens: {tokens}...")       
    print(f"Token IDs: {encoded_input['input_ids']}...")
    print("\n")
#     print("Length of the sentence is",len(sentence[0].split(" ")))
    print("Token shape for sentence is",np.array([tokens]).shape)
#     print("Length of Encoded Input of this sentence is",len(encoded_input['input_ids'][:50]))
    print("\n")
    print("*********************************************************\n")
    TOKEN_IDS.append(np.array(encoded_input['input_ids']))
    SEGMENT_IDS.append(np.array([i for j in range(36)]))
    i+=1

Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' truncation strategy. So the returned list will always be empty even if some tokens have been removed.
Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' truncation strategy. So the returned list will always be empty even if some tokens have been removed.
Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' truncation strategy. So the returned list will always be empty even if some tokens have been removed.


Question: What is Cybersecurity?...
Tokens: ['[CLS]', 'what', 'is', 'cyber', '##se', '##cu', '##rity', '?', '[SEP]', 'cyber', '##se', '##cu', '##rity', 'is', 'the', 'practice', 'of', 'protecting', 'systems', ',', 'networks', ',', 'and', 'programs', 'from', 'digital', 'attacks', ',', 'theft', ',', 'or', 'damage', '.', 'these', 'cyber', '##att', '##ack', '##s', 'usually', 'aim', 'to', 'access', ',', 'alter', ',', 'or', 'destroy', 'sensitive', 'information', ',', 'ex', '##tort', 'money', ',', 'or', 'disrupt', 'normal', 'business', 'operations', '.', 'key', 'components', 'include', ':', '-', 'network', 'security', ':', 'protecting', 'network', 'integrity', 'and', 'data', '.', '-', 'application', 'security', ':', 'securing', 'applications', 'by', 'identifying', 'vu', '##ln', '##era', '[SEP]']...
Token IDs: [101, 2054, 2003, 16941, 3366, 10841, 15780, 1029, 102, 16941, 3366, 10841, 15780, 2003, 1996, 3218, 1997, 8650, 3001, 1010, 6125, 1010, 1998, 3454, 2013, 3617, 4491, 1010, 11933, 1010, 2

In [2]:
import torch

def generate_positional_ids(sentences, max_length):
    
    positional_ids = torch.arange(max_length).unsqueeze(0).expand(len(sentences), -1)
    
    return positional_ids

# Example usage
max_length=86
  # Specify the maximum length
positional_ids = generate_positional_ids(long_sentences, max_length)

print(" Complete Positional IDs:\n", positional_ids)
print("Shapes are: ")
POSITIONAL_IDS=[]
for tensors in positional_ids:
    print("********************************************")
    print(tensors)
    print(np.array([tensors]).shape)
    print("********************************************")
    POSITIONAL_IDS.append(np.array(tensors))

 Complete Positional IDs:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41

In [3]:
TOKEN_IDS=np.array(TOKEN_IDS)
POSITIONAL_IDS=np.array(POSITIONAL_IDS)

In [4]:
print(TOKEN_IDS.shape)
# print(SEGMENT_IDS.shape)
print(POSITIONAL_IDS.shape)

(3, 86)
(3, 86)


In [5]:
combined_ids=TOKEN_IDS+POSITIONAL_IDS
print(combined_ids.shape)

(3, 86)


In [6]:
combined_ids

array([[  101,  2055,  2005, 16944,  3370, 10846, 15786,  1036,   110,
        16950,  3376, 10852, 15792,  2016,  2010,  3233,  2013,  8667,
         3019,  1029,  6145,  1031,  2020,  3477,  2037,  3642,  4517,
         1037, 11961,  1039,  2060,  4084,  1044,  2155, 16975, 19356,
         8720,  2052,  2826,  6653,  2040,  3270,  1052, 11520,  1054,
         2075,  6079,  7638,  2640,  1059,  4704, 25536,  2821,  1063,
         2084, 23272,  3727,  2506,  3194,  1071,  3205,  6238,  2483,
         1087,  1075,  2962,  3102,  1091,  8718,  2966, 11179,  2069,
         3023,  1085,  1085,  4721,  3112,  1101, 12407,  5176,  2091,
        12232, 24810, 19749,  6990,   187],
       [  101,  2055,  2005, 15454,  8063,  1034,   108, 15458,  8067,
         1019,  2470,  2016, 24403,  4020,  1024,  5233,  2016,  2168,
         4025,  2900,  2020,  3447,  7408,  2023,  1061,  3299,  1036,
         2924,  1038,  2059,  8271,  1043,  2041,  2036,  2143,  2046,
        17893,  2037,  8992,  299

In [7]:
import torch
import torch.nn as nn


def generate_token_embeddings(token_ids, vocab_size, hidden_size):
   
    embedding_layer = nn.Embedding(vocab_size, hidden_size)

    
    token_tensor = torch.nn.utils.rnn.pad_sequence(
        [torch.tensor(tokens) for tokens in token_ids],
        batch_first=True
    )


    embeddings = embedding_layer(token_tensor)

    return embeddings


vocab_size = 30522
hidden_size = 768

token_embeddings = generate_token_embeddings(TOKEN_IDS, vocab_size, hidden_size)

print("Token Embeddings Shape:", token_embeddings.shape)  

for i in range(len(long_sentences)):
    print("\nToken Embeddings for Sentence:\n",i, token_embeddings[i])
    print("Shape of the tensor: ",token_embeddings[i].shape)
    print("***************************************************************8")
    
print("Final Token Embeddings Shape: \n",token_embeddings.shape)

Token Embeddings Shape: torch.Size([3, 86, 768])

Token Embeddings for Sentence:
 0 tensor([[-1.3173, -0.4889, -2.0296,  ..., -1.2706, -0.0596,  0.0905],
        [ 0.1539, -0.1608,  0.7088,  ..., -0.0658,  0.5019, -2.0494],
        [ 1.1148,  0.3157, -0.9515,  ..., -0.1460,  0.2515, -0.2113],
        ...,
        [ 0.4355,  0.0764, -1.8080,  ...,  0.7615,  0.8738,  0.4637],
        [-0.1186,  1.3766,  0.8951,  ..., -0.1377, -1.4444,  1.6697],
        [ 1.4173,  1.0788,  0.5447,  ...,  0.0247,  0.4963,  0.2345]],
       grad_fn=<SelectBackward0>)
Shape of the tensor:  torch.Size([86, 768])
***************************************************************8

Token Embeddings for Sentence:
 1 tensor([[-1.3173, -0.4889, -2.0296,  ..., -1.2706, -0.0596,  0.0905],
        [ 0.1539, -0.1608,  0.7088,  ..., -0.0658,  0.5019, -2.0494],
        [ 1.1148,  0.3157, -0.9515,  ..., -0.1460,  0.2515, -0.2113],
        ...,
        [-0.8480,  0.4784, -1.2368,  ..., -0.9439, -0.0796,  1.1984],
        [ 0

In [8]:
import torch
import torch.nn as nn

def generate_positional_embeddings(batch_size, max_length, hidden_size):
    positional_embeddings = nn.Embedding(max_length, hidden_size)
    positional_ids = torch.arange(max_length)
    embeddings = positional_embeddings(positional_ids)
    positional_embeddings_with_batch = embeddings.unsqueeze(0).expand(batch_size, -1, -1)
    return positional_embeddings_with_batch

batch_size = 3
max_length = 86
hidden_size = 768  

positional_embeddings = generate_positional_embeddings(batch_size, max_length, hidden_size)
for i in range(batch_size):
    print("Positional Embeddings:", positional_embeddings[i])
    print("Shape: ",positional_embeddings[i].shape)
    print("********************************************************************\n")
print("\nFinal Positional Embeddings Shape:\n", positional_embeddings.shape)


Positional Embeddings: tensor([[-0.1937, -1.6509,  0.0524,  ..., -0.3078, -0.8161,  0.1402],
        [-0.1640, -0.5365,  2.5154,  ...,  0.1293, -1.5503,  0.0813],
        [ 0.2446, -1.1862,  0.5611,  ...,  1.9334,  0.3556, -0.2372],
        ...,
        [ 0.8061,  1.6361,  1.4724,  ...,  0.9765, -0.0786, -0.9160],
        [-0.8116,  0.4125, -2.3977,  ..., -0.7698, -0.9078, -1.2793],
        [-0.5043,  1.4386, -0.0188,  ...,  1.1596, -0.1285, -0.9348]],
       grad_fn=<SelectBackward0>)
Shape:  torch.Size([86, 768])
********************************************************************

Positional Embeddings: tensor([[-0.1937, -1.6509,  0.0524,  ..., -0.3078, -0.8161,  0.1402],
        [-0.1640, -0.5365,  2.5154,  ...,  0.1293, -1.5503,  0.0813],
        [ 0.2446, -1.1862,  0.5611,  ...,  1.9334,  0.3556, -0.2372],
        ...,
        [ 0.8061,  1.6361,  1.4724,  ...,  0.9765, -0.0786, -0.9160],
        [-0.8116,  0.4125, -2.3977,  ..., -0.7698, -0.9078, -1.2793],
        [-0.5043,  1.43

In [9]:
import torch
import torch.nn as nn

def generate_segment_embeddings(segment_ids, hidden_size):
    # Create an embedding layer for two segments (0 and 1)
    segment_embeddings = nn.Embedding(2, hidden_size)
    
    # Get the segment embeddings using the segment IDs
    embeddings = segment_embeddings(segment_ids)
    
    return embeddings

# Example parameters
batch_size = 3
max_length = 86
hidden_size = 768  

# Example segment IDs: a tensor of shape (batch_size, max_length)
# Here, the first half is segment 0 and the second half is segment 1
SEGMENT_IDS = torch.zeros((batch_size, max_length), dtype=torch.long)
SEGMENT_IDS[:, max_length // 2:] = 1

# Generate segment embeddings
segment_embeddings = generate_segment_embeddings(SEGMENT_IDS, hidden_size)
for i in range(batch_size):
    print("Segment Embedding: ",segment_embeddings[i])
    print("Shape: ",segment_embeddings[i].shape)
    print("***************************************************************************")
# Output shape and embeddingsape:", segment_embeddings.shape)  # Should be (batch_size, max_length, hidden_size)
print("\nFinal Segment Embeddings:\n", segment_embeddings.shape)


Segment Embedding:  tensor([[ 0.6256,  0.3246,  1.9778,  ...,  1.2585, -1.8255,  0.1230],
        [ 0.6256,  0.3246,  1.9778,  ...,  1.2585, -1.8255,  0.1230],
        [ 0.6256,  0.3246,  1.9778,  ...,  1.2585, -1.8255,  0.1230],
        ...,
        [-1.2266, -1.6429,  1.3023,  ..., -0.3819,  0.8702,  2.4243],
        [-1.2266, -1.6429,  1.3023,  ..., -0.3819,  0.8702,  2.4243],
        [-1.2266, -1.6429,  1.3023,  ..., -0.3819,  0.8702,  2.4243]],
       grad_fn=<SelectBackward0>)
Shape:  torch.Size([86, 768])
***************************************************************************
Segment Embedding:  tensor([[ 0.6256,  0.3246,  1.9778,  ...,  1.2585, -1.8255,  0.1230],
        [ 0.6256,  0.3246,  1.9778,  ...,  1.2585, -1.8255,  0.1230],
        [ 0.6256,  0.3246,  1.9778,  ...,  1.2585, -1.8255,  0.1230],
        ...,
        [-1.2266, -1.6429,  1.3023,  ..., -0.3819,  0.8702,  2.4243],
        [-1.2266, -1.6429,  1.3023,  ..., -0.3819,  0.8702,  2.4243],
        [-1.2266, -1.64

In [10]:
combined_embeddings=token_embeddings+positional_embeddings
combined_embeddings.shape

torch.Size([3, 86, 768])

In [11]:
combined_embeddings

tensor([[[-1.5110, -2.1397, -1.9772,  ..., -1.5784, -0.8757,  0.2308],
         [-0.0100, -0.6972,  3.2242,  ...,  0.0634, -1.0484, -1.9681],
         [ 1.3594, -0.8706, -0.3903,  ...,  1.7874,  0.6071, -0.4485],
         ...,
         [ 1.2416,  1.7125, -0.3357,  ...,  1.7380,  0.7953, -0.4523],
         [-0.9303,  1.7891, -1.5026,  ..., -0.9074, -2.3523,  0.3905],
         [ 0.9130,  2.5174,  0.5259,  ...,  1.1844,  0.3677, -0.7003]],

        [[-1.5110, -2.1397, -1.9772,  ..., -1.5784, -0.8757,  0.2308],
         [-0.0100, -0.6972,  3.2242,  ...,  0.0634, -1.0484, -1.9681],
         [ 1.3594, -0.8706, -0.3903,  ...,  1.7874,  0.6071, -0.4485],
         ...,
         [-0.0419,  2.1145,  0.2356,  ...,  0.0326, -0.1581,  0.2824],
         [-0.5758,  1.8425, -2.8155,  ..., -1.5366, -1.0282, -2.1409],
         [ 0.9130,  2.5174,  0.5259,  ...,  1.1844,  0.3677, -0.7003]],

        [[-1.5110, -2.1397, -1.9772,  ..., -1.5784, -0.8757,  0.2308],
         [-0.0100, -0.6972,  3.2242,  ...,  0

In [12]:
import torch

def generate_attention_mask(combined_embeddings):
    batch_size, max_length, _ = combined_embeddings.shape
    
    attention_mask = (combined_embeddings != 0).any(dim=-1).long()
    
    return attention_mask

batch_size = 3
max_length = 86
hidden_size = 768


combined_embeddings = torch.rand((batch_size, max_length, hidden_size))  

attention_mask = generate_attention_mask(combined_embeddings)


print("Attention Mask Shape:", attention_mask.shape)  
print("Attention Mask:\n", attention_mask)


Attention Mask Shape: torch.Size([3, 86])
Attention Mask:
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])


In [13]:
import torch
import torch.nn as nn

class MultiHeadAttention(nn.Module):
    def __init__(self, hidden_size, num_heads):
        super(MultiHeadAttention, self).__init__()
        self.num_heads = num_heads
        self.head_dim = hidden_size // num_heads

        assert (
            hidden_size % num_heads == 0
        ), "hidden_size must be divisible by num_heads"

        self.query_linear = nn.Linear(hidden_size, hidden_size)
        self.key_linear = nn.Linear(hidden_size, hidden_size)
        self.value_linear = nn.Linear(hidden_size, hidden_size)
        self.fc_out = nn.Linear(hidden_size, hidden_size)

    def forward(self, x):
        batch_size, seq_length, hidden_size = x.size()

        queries = self.query_linear(x)  
        keys = self.key_linear(x)
        values = self.value_linear(x)

        # Print the query, key, and value matrices
        print("\nQueries Matrix:- ",queries)
        print("Queries Matrix Shape:", queries.shape)
        print("\nKeys Matrix:- ",keys)
        print("Keys Matrix Shape:", keys.shape)
        print("\nValues Matrix:- ",values)
        print("Values Matrix Shape:", values.shape)

        # Reshape for multi-head attention
        queries = queries.view(batch_size, seq_length, self.num_heads, self.head_dim).transpose(1, 2)  # (batch_size, num_heads, seq_length, head_dim)
        keys = keys.view(batch_size, seq_length, self.num_heads, self.head_dim).transpose(1, 2)  # (batch_size, num_heads, seq_length, head_dim)
        values = values.view(batch_size, seq_length, self.num_heads, self.head_dim).transpose(1, 2)  # (batch_size, num_heads, seq_length, head_dim)
        energy = torch.einsum("nhqd,nhkd->nhqk", [queries, keys])  # (batch_size, num_heads, seq_length, seq_length)

        attention_scores = energy / (self.head_dim ** 0.5)
        print("Attention scores shape: ",attention_scores.shape)
        attention = torch.softmax(energy / (self.head_dim ** 0.5), dim=3)  # Scale and softmax
        print("Attention score shape after softmax: ",attention.shape)
        out = torch.einsum("nhql,nhld->nhqd", [attention, values]).reshape(batch_size, seq_length, hidden_size)  # (batch_size, seq_length, hidden_size)
        out = self.fc_out(out)  # Final linear layer

        return out


batch_size = 3
seq_length = 86
hidden_size = 768
num_heads = 12

attention_layer = MultiHeadAttention(hidden_size, num_heads)


combined_embeddings = combined_embeddings


output_embeddings = attention_layer(combined_embeddings)

print("Output Embeddings Shape:", output_embeddings.shape)  




Queries Matrix:-  tensor([[[ 3.7528e-01,  3.3901e-01,  1.6776e-01,  ..., -2.0755e-01,
           1.9805e-01, -3.8161e-01],
         [ 6.5055e-01,  3.7887e-01,  2.8131e-01,  ..., -2.2844e-01,
          -4.9036e-02, -3.6855e-01],
         [ 4.4325e-01,  9.6339e-02,  3.6114e-01,  ...,  6.7594e-02,
          -1.3883e-01, -5.4448e-01],
         ...,
         [ 6.7491e-01,  3.2428e-01,  1.1466e-01,  ..., -1.5083e-02,
           1.0284e-01,  7.9355e-03],
         [ 5.2081e-01,  3.7057e-01,  1.5774e-01,  ...,  1.7238e-02,
           3.2366e-03, -4.1652e-01],
         [ 5.4127e-01,  2.7732e-01, -1.5818e-01,  ..., -1.1622e-01,
           2.4825e-01, -4.5236e-01]],

        [[ 4.5222e-01,  3.1255e-02,  4.1047e-01,  ..., -2.5653e-02,
          -1.2489e-01, -3.6059e-01],
         [ 6.5078e-01,  4.9359e-01,  2.7908e-01,  ..., -3.0817e-01,
           2.0650e-01, -2.9903e-01],
         [ 9.2715e-01,  2.3311e-01, -1.8400e-02,  ...,  1.2806e-01,
          -2.7711e-02, -3.5027e-01],
         ...,
      

In [14]:
output_embeddings

tensor([[[ 0.1186, -0.2490, -0.1706,  ..., -0.0857, -0.0484, -0.2073],
         [ 0.1186, -0.2490, -0.1711,  ..., -0.0852, -0.0487, -0.2075],
         [ 0.1186, -0.2492, -0.1708,  ..., -0.0858, -0.0486, -0.2071],
         ...,
         [-0.0590,  0.0368, -0.1373,  ..., -0.0091, -0.0807,  0.0887],
         [-0.0586,  0.0376, -0.1377,  ..., -0.0091, -0.0818,  0.0887],
         [-0.0591,  0.0367, -0.1376,  ..., -0.0092, -0.0817,  0.0881]],

        [[ 0.1228, -0.2434, -0.1613,  ..., -0.0692, -0.0629, -0.1992],
         [ 0.1235, -0.2444, -0.1609,  ..., -0.0690, -0.0635, -0.1996],
         [ 0.1230, -0.2449, -0.1609,  ..., -0.0698, -0.0632, -0.1996],
         ...,
         [-0.0963,  0.0454, -0.1496,  ..., -0.0212, -0.0903,  0.1068],
         [-0.0957,  0.0450, -0.1501,  ..., -0.0208, -0.0903,  0.1067],
         [-0.0958,  0.0452, -0.1489,  ..., -0.0212, -0.0904,  0.1063]],

        [[ 0.1270, -0.2272, -0.1631,  ..., -0.0776, -0.0595, -0.2086],
         [ 0.1272, -0.2273, -0.1627,  ..., -0

In [15]:
class QAHead(nn.Module):
    def __init__(self, hidden_size):
        super(QAHead, self).__init__()
        self.start_logits = nn.Linear(hidden_size, 1)
        self.end_logits = nn.Linear(hidden_size, 1)

    def forward(self, embeddings):
        start_logits = self.start_logits(embeddings).squeeze(-1)  
        end_logits = self.end_logits(embeddings).squeeze(-1)      
        return start_logits, end_logits


In [16]:
qa_head = QAHead(hidden_size)
start_logits, end_logits = qa_head(output_embeddings)

print("Start Logits Shape:", start_logits.shape)  
print("End Logits Shape:", end_logits.shape)      


Start Logits Shape: torch.Size([3, 86])
End Logits Shape: torch.Size([3, 86])


In [17]:
start_logits,end_logits

(tensor([[-0.1136, -0.1135, -0.1134, -0.1134, -0.1133, -0.1133, -0.1133,  0.0131,
           0.0237,  0.0236,  0.0236,  0.0234,  0.0237,  0.0237, -0.0810, -0.0051,
          -0.0051, -0.0050, -0.0054, -0.0051, -0.0054,  0.0667,  0.0439,  0.0437,
           0.0439,  0.0440,  0.0442,  0.0440, -0.0736, -0.1884, -0.1882, -0.1884,
          -0.1888, -0.1887, -0.1884, -0.0981, -0.1854, -0.1853, -0.1854, -0.1855,
          -0.1857, -0.1856, -0.1854, -0.2822, -0.2826, -0.2825, -0.2825, -0.2826,
          -0.2826, -0.2823, -0.2079, -0.2043, -0.2042, -0.2044, -0.2039, -0.2042,
          -0.2043, -0.1205, -0.0337, -0.0336, -0.0337, -0.0338, -0.0338, -0.0334,
           0.0836,  0.0182,  0.0183,  0.0182,  0.0185,  0.0184,  0.0184,  0.0386,
          -0.0073, -0.0077, -0.0074, -0.0074, -0.0077, -0.0074, -0.0504, -0.1613,
          -0.1612, -0.1613, -0.1613, -0.1612, -0.1612, -0.1612],
         [-0.1192, -0.1189, -0.1191, -0.1191, -0.1190, -0.1191, -0.1191,  0.0302,
           0.0378,  0.0376,  0.03

In [18]:
start_positions = torch.argmax(start_logits, dim=-1)
end_positions = torch.argmax(end_logits, dim=-1)
start_positions,end_positions

(tensor([64, 64, 64]), tensor([28, 28, 28]))

In [19]:
idx=0
for l in long_sentences:
    print("Question 1:")
    print(l[0])
    print(l[1][start_positions[idx]:end_positions[idx]])
    idx+=1

Question 1:
What is Cybersecurity?

Question 1:
What is Malware?

Question 1:
What is Phishing?

